###################################################################################################

- name : patch

  hosts: all

  gather_facts: false

  roles:

    -   role: bootstrap

    - { role: platform/package/patch,
        patch_update    : true ,
        patch_upgrade   : true ,
        patch_autoclean : true ,
        patch_autoremove: true }

    -   role: platform/bounce

  tags:
    - artemis
    - platform
    - package
    - patch

###################################################################################################
