###################################################################################################

- name: import | family

  include_vars: '{{ os_family_lower }}'

  tags:
    - artemis
    - platform
    - firewall

###################################################################################################

- name: import | security | balanced

  when: security_mode_inc_balanced

  include_vars: '{{ security_word }}-{{ security_mode_balanced }}'

  tags:
    - artemis
    - platform
    - firewall

###################################################################################################

- name: import | security | enhanced

  when: security_mode_inc_enhanced

  include_vars: '{{ security_word }}-{{ security_mode_enhanced }}'

  tags:
    - artemis
    - platform
    - firewall

###################################################################################################

- name: import | overrides

  when: overrides_verified

  include_vars: '{{ overrides_path }}'

  tags:
    - artemis
    - platform
    - firewall

###################################################################################################

- name: debian

  when: os_family_is_debian

  include: debian.yml
  static : false

  tags:
    - artemis
    - platform
    - firewall
    - debian

###################################################################################################

- name: redhat

  when: os_family_is_redhat

  include: redhat.yml
  static : false

  tags:
    - artemis
    - platform
    - firewall
    - redhat

###################################################################################################
