###################################################################################################

- name: redhat | dependencies

  become: true

  with_items: '{{ firewall_dependencies }}'

  yum : name={{ item }} state=present

  tags:
    - artemis
    - platform
    - firewall
    - redhat

###################################################################################################

- name: redhat | enable

  when: firewall_enabled

  become: true

  service: name={{ firewall_service }} enabled=true

  tags:
    - artemis
    - platform
    - firewall
    - redhat

###################################################################################################

- name: redhat | start

  when: firewall_enabled

  become: true

  service: name={{ firewall_service }} state=started

  tags:
    - artemis
    - platform
    - firewall
    - redhat

###################################################################################################

- name: redhat | stop

  when: not firewall_enabled

  become: true

  service: name={{ firewall_service }} state=stopped

  tags:
    - artemis
    - platform
    - firewall
    - redhat

###################################################################################################

- name: redhat | disable

  when: not firewall_enabled

  become: true

  service: name={{ firewall_service }} enabled=false

  tags:
    - artemis
    - platform
    - firewall
    - redhat

###################################################################################################

- name: redhat | ssh

  when: firewall_enabled

  become: true

  firewalld: port={{ firewall_ssh_port }}/{{ firewall_ssh_proto }} state=enabled permanent=true

  register: ssh

  tags:
    - artemis
    - platform
    - firewall
    - redhat

###################################################################################################

- name: redhat | restart

  when: ssh.changed

  become: true

  service: name={{ firewall_service }} state=restarted

  tags:
    - artemis
    - platform
    - firewall
    - redhat

###################################################################################################

- name: redhat | start

  when: ssh.changed

  become: true

  service: name={{ firewall_service }} state=started

  tags:
    - artemis
    - platform
    - firewall
    - redhat

###################################################################################################
