###################################################################################################

- name: set | stop

  become: true

  service: name={{ ntpd_service }} state=stopped

  tags:
    - artemis
    - platform
    - ntpd
    - set

###################################################################################################

- name: set | date

  become: true

  command: '{{ ntpd_set_command }}'

  tags:
    - artemis
    - platform
    - ntpd
    - set

###################################################################################################
