###################################################################################################

- name: debian | upgrade

  when: patch_upgrade

  become: true

  apt : update_cache={{ patch_update      }}
        autoremove={{   patch_autoremove  }}
        upgrade={{      patch_apt_upgrade }}

  register: upgrade

  tags:
    - artemis
    - platform
    - package
    - patch
    - debian

###################################################################################################

- name: debian | clean

  when: patch_autoclean
    and upgrade.changed

  become: true

  command: apt-get clean

  tags:
    - artemis
    - platform
    - package
    - patch
    - debian

###################################################################################################

- name: debian | signals

  when: upgrade.changed

  set_fact:
    bounce : true
    patched: true

  tags:
    - artemis
    - platform
    - package
    - patch
    - debian

###################################################################################################
